let deferredInstallPrompt=null;
const MAINTENANCE_VAPID_PUBLIC_KEY='BIgeqHk1a0UkimLlKLJn0OWEyASbTaE5ykjw36HIvnm6hW7COzXBvODsn8nW0leEVvKBZV_sw4eiV0r8aKurEiw';
function isStandaloneApp(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;toast('تم تثبيت تطبيق إدارة الصيانة')});
function sortMaintenanceRows(rows=[]){const priorityRank={emergency:0,urgent:1,normal:2,improvement:3};return [...rows].sort((a,b)=>{const ac=['completed','cancelled'].includes(a.status)?1:0,bc=['completed','cancelled'].includes(b.status)?1:0;if(ac!==bc)return ac-bc;const p=(priorityRank[a.priority]??9)-(priorityRank[b.priority]??9);return p||new Date(a.created_at)-new Date(b.created_at)})}
function maintenanceListHtml(rows=[]){if(!rows?.length)return'<div class="empty">لا توجد طلبات حتى الآن.</div>';const critical=rows.filter(r=>!['completed','cancelled'].includes(r.status)&&['emergency','urgent'].includes(r.priority));if(!critical.length)return ticketList(rows);const ids=new Set(critical.map(r=>r.id)),rest=rows.filter(r=>!ids.has(r.id));return `<div class="priority-section"><div class="priority-section-title">⚠️ طلبات تحتاج اهتمام مباشر</div>${ticketList(critical)}</div>${rest.length?`<div><div class="regular-section-title">باقي الطلبات</div>${ticketList(rest)}</div>`:''}`}
function installPanelHtml(){if(state.profile?.role!=='maintenance'||isStandaloneApp())return'';return `<div class="notification-panel"><div><strong>📲 تطبيق إدارة الصيانة</strong><p>ثبّته على شاشة الجوال لفتح متابعة الصيانة مباشرة مثل أي تطبيق.</p></div><button class="btn gold" id="installMaintenanceApp">تثبيت تطبيق إدارة الصيانة</button></div>`}
function notificationPanelHtml(){const install=installPanelHtml();if(state.profile?.role!=='maintenance')return install;if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))return install+'<div class="notification-panel"><strong>🔕 الإشعارات غير مدعومة</strong></div>';const denied=Notification.permission==='denied';return install+`<div class="notification-panel"><div><strong id="notificationTitle">🔔 إشعارات طلبات الصيانة</strong><p id="notificationText">${denied?'الإشعارات محظورة من إعدادات المتصفح.':'فعّلها مرة واحدة ليصلك تنبيه عند وصول طلب جديد.'}</p></div><button class="btn ${denied?'ghost':'gold'}" id="enableNotifications" ${denied?'disabled':''}>${denied?'الإشعارات محظورة':'تفعيل إشعارات الجوال'}</button></div>`}
async function installMaintenanceApp(){await registerMaintenanceServiceWorker();if(deferredInstallPrompt){deferredInstallPrompt.prompt();const result=await deferredInstallPrompt.userChoice.catch(()=>null);if(result?.outcome==='accepted')toast('جاري تثبيت إدارة الصيانة');deferredInstallPrompt=null;return}const msg=/Android/i.test(navigator.userAgent)?'إذا لم تظهر نافذة التثبيت: اضغط ⋮ في Chrome ثم «إضافة إلى الشاشة الرئيسية» أو «تثبيت التطبيق».':'من قائمة المتصفح اختر «إضافة إلى الشاشة الرئيسية».';toast(msg);const b=document.getElementById('installMaintenanceApp');if(b)b.insertAdjacentHTML('afterend',`<div class="hint" style="margin-top:8px">${msg}</div>`)}
function urlBase64ToUint8Array(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b);return Uint8Array.from([...r].map(c=>c.charCodeAt(0)))}
function arrayBufferToBase64Url(buffer){let x='';new Uint8Array(buffer).forEach(v=>x+=String.fromCharCode(v));return btoa(x).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function registerMaintenanceServiceWorker(){if(!('serviceWorker'in navigator))return null;try{return await navigator.serviceWorker.register('/manager-sw.js',{scope:'/'})}catch(e){console.warn(e);return null}}
async function savePushSubscription(subscription){const j=subscription.toJSON(),p=j.keys?.p256dh||arrayBufferToBase64Url(subscription.getKey('p256dh')),a=j.keys?.auth||arrayBufferToBase64Url(subscription.getKey('auth'));await api('/rest/v1/maintenance_push_subscriptions?on_conflict=endpoint',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:state.user.id,endpoint:subscription.endpoint,p256dh:p,auth:a,user_agent:navigator.userAgent})})}
async function enableMaintenancePush(){const btn=document.getElementById('enableNotifications');try{await registerMaintenanceServiceWorker();if(await Notification.requestPermission()!=='granted')throw Error('لم يتم السماح بالإشعارات');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(MAINTENANCE_VAPID_PUBLIC_KEY)});await savePushSubscription(sub);if(btn){btn.textContent='الإشعارات مفعّلة';btn.disabled=true}toast('تم تفعيل إشعارات الصيانة')}catch(e){toast('تعذر تفعيل الإشعارات')}}
function bindNotificationPanel(){const install=document.getElementById('installMaintenanceApp');if(install)install.onclick=installMaintenanceApp;const btn=document.getElementById('enableNotifications');if(btn&&!btn.disabled)btn.onclick=enableMaintenancePush}
async function notifyMaintenanceNewRequest(requestId){if(!requestId||!state.session?.access_token)return;const res=await fetch(`${SUPABASE_URL}/functions/v1/send-maintenance-push`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${state.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({request_id:requestId})});if(!res.ok)throw Error(`Push HTTP ${res.status}`);return res.json()}
registerMaintenanceServiceWorker();