(()=>{'use strict';
let raf=0;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
function isText(el,t){return (el?.textContent||'').trim()===t}
function markTop(){const top=q('.top');if(!top)return;top.classList.add('pro-clean-top');q('.logo',top)?.remove();const user=q('.userlabel',top);if(user&&isText(user,'المدير'))user.remove()}
function enhanceManager(){const h2=qa('.head h2').find(x=>isText(x,'لوحة المدير'));if(!h2)return false;document.body.classList.add('pro-manager-dashboard');document.body.classList.remove('pro-admin-page');const shell=h2.closest('.shell');shell?.classList.add('manager-shell');const head=h2.closest('.head');head?.classList.add('manager-hero');const dash=q('#dash');if(!dash)return true;dash.classList.add('manager-grid');qa('.dash',dash).forEach((card,i)=>{if(card.dataset.managerReady==='1')return;card.dataset.managerReady='1';card.classList.add('manager-branch-card');const status=q('.status',card);if(status){if(status.classList.contains('ok'))card.classList.add('report-ok');else if(status.classList.contains('draft'))card.classList.add('report-draft');else card.classList.add('report-miss')}
 const title=q('h3',card),meta=q('.meta',card),open=q('.open',card);if(title&&status&&!q('.manager-card-head',card)){const wrap=document.createElement('div');wrap.className='manager-card-head';title.before(wrap);wrap.append(title,status)}if(open)open.classList.add('manager-open-report');if(meta)meta.classList.add('manager-card-meta')});
 const cards=qa('.dash',dash);if(cards.length&&!q('.manager-summary',shell)){const ok=cards.filter(c=>c.classList.contains('report-ok')).length,draft=cards.filter(c=>c.classList.contains('report-draft')).length,miss=cards.filter(c=>c.classList.contains('report-miss')).length;const s=document.createElement('div');s.className='manager-summary';s.innerHTML=`<span><b>${cards.length}</b> فروع</span><span class="sum-ok"><b>${ok}</b> معتمد</span><span class="sum-wait"><b>${draft+miss}</b> بانتظار الإكمال</span>`;head?.insertAdjacentElement('afterend',s)}else if(cards.length){const s=q('.manager-summary',shell),vals=s?qa('b',s):[];if(vals.length>=3){vals[0].textContent=cards.length;vals[1].textContent=cards.filter(c=>c.classList.contains('report-ok')).length;vals[2].textContent=cards.filter(c=>!c.classList.contains('report-ok')).length}}
 return true}
function enhanceAdmin(){const table=q('.admin-accordion')||q('.admintable,.admin-table');const form=q('.adminform,.admin-form');if(!table&&!form)return false;const h2=qa('.head h2').find(x=>(x.textContent||'').includes('إدارة'));if(!h2)return false;document.body.classList.add('pro-admin-page');document.body.classList.remove('pro-manager-dashboard');h2.closest('.shell')?.classList.add('admin-shell');h2.closest('.head')?.classList.add('admin-page-head');return true}
function run(){markTop();if(!enhanceManager())enhanceAdmin()}
function schedule(){cancelAnimationFrame(raf);raf=requestAnimationFrame(run)}
new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
