(()=>{'use strict';
const VER='report-v19';
if(window.__reportV19Loaded)return;window.__reportV19Loaded=true;
const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const txt=el=>String(el?.textContent||'').trim();
const hasVal=el=>!!el&&el.value!==''&&el.value!==null&&el.value!==undefined;
const PAGE={W:1080,H:1920,M:42,TOP:320,BOTTOM:1834,GAP:14,COLS:3};
PAGE.CW=(PAGE.W-PAGE.M*2-PAGE.GAP*(PAGE.COLS-1))/PAGE.COLS;PAGE.BH=PAGE.BOTTOM-PAGE.TOP;
function toast(msg,bad=false){let t=document.querySelector('.report-v19-toast');if(!t){t=document.createElement('div');t.className='report-v19-toast';Object.assign(t.style,{position:'fixed',left:'18px',bottom:'86px',zIndex:'99999',padding:'10px 14px',borderRadius:'10px',font:'700 12px Tahoma,Arial',color:'#fff',background:'#2f2a23',boxShadow:'0 8px 24px rgba(0,0,0,.18)',transition:'.18s',opacity:'0'});document.body.appendChild(t)}t.textContent=msg;t.style.background=bad?'#9f433b':'#2f2a23';t.style.opacity='1';clearTimeout(window.__rv19);window.__rv19=setTimeout(()=>t.style.opacity='0',2800)}
function currentReport(){const branch=txt(document.querySelector('.head h2'))||'الفرع';const meta=txt(document.querySelector('.head .muted'));const notes=(document.querySelector('#notes')?.value||'').trim();const sections=qsa('.section').map(sec=>{const title=txt(sec.querySelector('.sectitle h3'))||'قسم';const table=sec.querySelector('table.flow');if(table){const items=qsa('tbody tr',table).map(row=>{const closing=row.querySelector('input[data-key="closing"]');if(!hasVal(closing))return null;const cells=row.querySelectorAll('td');return{name:txt(cells[0]),opening:txt(row.querySelector('.ro'))||'0',incoming:String(row.querySelector('input[data-key="incoming"]')?.value||'0'),closing:String(closing.value),sold:txt(row.querySelector('.sold'))||'—',unit:txt(cells[cells.length-1])}}).filter(Boolean);return items.length?{title,type:'flow',items}:null}const items=qsa('.item',sec).map(card=>{const input=card.querySelector('input[data-key="value"]');if(!hasVal(input))return null;return{name:txt(card.querySelector('.name')),value:String(input.value),unit:txt(card.querySelector('.unit'))}}).filter(Boolean);return items.length?{title,type:'simple',items}:null}).filter(Boolean);return{branch,meta,notes,sections,date:document.querySelector('#rd')?.value||new Date().toISOString().slice(0,10)}}
function pathRound(c,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+rr,y);c.arcTo(x+w,y,x+w,y+h,rr);c.arcTo(x+w,y+h,x,y+h,rr);c.arcTo(x,y+h,x,y,rr);c.arcTo(x,y,x+w,y,rr);c.closePath()}
function cardBox(c,x,y,w,h,r,fill,stroke,shadow=true){c.save();if(shadow){c.shadowColor='rgba(72,50,20,.10)';c.shadowBlur=10;c.shadowOffsetY=3}pathRound(c,x,y,w,h,r);c.fillStyle=fill;c.fill();c.restore();if(stroke){pathRound(c,x,y,w,h,r);c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}}
function fit(c,text,max,size=18,min=11,weight='700'){let s=size;for(;s>min;s--){c.font=`${weight} ${s}px Tahoma,Arial`;if(c.measureText(String(text)).width<=max)break}return s}
function ellipsis(c,text,max){let s=String(text);if(c.measureText(s).width<=max)return s;while(s.length>2&&c.measureText(s+'…').width>max)s=s.slice(0,-1);return s+'…'}
function image(src){return new Promise(res=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>res(null);im.src=src})}
function rowH(sec){return sec.type==='flow'?44:sec.type==='notes'?92:32}
function cardH(sec){return 50+sec.items.length*rowH(sec)+12}
function splitSections(report){const source=[...report.sections];if(report.notes)source.push({title:'ملاحظات',type:'notes',items:[{name:report.notes}]});const out=[];for(const sec of source){const rh=rowH(sec),max=Math.max(1,Math.floor((PAGE.BH-62)/rh));for(let i=0;i<sec.items.length;i+=max){out.push({title:sec.title,type:sec.type,items:sec.items.slice(i,i+max),part:i===0?0:Math.floor(i/max)+1})}}return out}
function layout(report){const chunks=splitSections(report),pages=[];let page=null;function fresh(){page={ys:Array(PAGE.COLS).fill(PAGE.TOP),cards:[]};pages.push(page)}fresh();for(const sec of chunks){const h=cardH(sec);let order=page.ys.map((y,i)=>({y,i})).sort((a,b)=>a.y-b.y),slot=order.find(o=>o.y+h<=PAGE.BOTTOM);if(!slot){fresh();order=page.ys.map((y,i)=>({y,i})).sort((a,b)=>a.y-b.y);slot=order[0]}const col=slot.i,x=PAGE.M+(PAGE.COLS-1-col)*(PAGE.CW+PAGE.GAP),y=page.ys[col];page.cards.push({sec,x,y,w:PAGE.CW,h});page.ys[col]=y+h+PAGE.GAP}return pages}
function drawBorder(c){c.strokeStyle='#b78b42';c.lineWidth=2;pathRound(c,12,12,PAGE.W-24,PAGE.H-24,22);c.stroke();c.strokeStyle='#e6d0a4';c.lineWidth=1;pathRound(c,20,20,PAGE.W-40,PAGE.H-40,18);c.stroke()}
function drawHeader(c,report,logo,pageNo,pageCount){if(logo){const maxW=410,maxH=86,scale=Math.min(maxW/logo.naturalWidth,maxH/logo.naturalHeight),w=logo.naturalWidth*scale,h=logo.naturalHeight*scale;c.drawImage(logo,(PAGE.W-w)/2,34,w,h)}c.direction='rtl';c.textAlign='center';c.fillStyle='#9d701f';c.font='800 42px Tahoma,Arial';c.fillText('تقرير الجرد اليومي',PAGE.W/2,151);c.fillStyle='#6f5630';c.font='600 20px Tahoma,Arial';c.fillText('لوحة الجرد اليومية',PAGE.W/2,183);c.strokeStyle='#c69a4e';c.lineWidth=1;c.beginPath();c.moveTo(PAGE.W/2-92,198);c.lineTo(PAGE.W/2+92,198);c.stroke();c.fillStyle='#2f2922';c.font='800 25px Tahoma,Arial';c.fillText(report.branch,PAGE.W/2,235);c.fillStyle='#756b5f';c.font='15px Tahoma,Arial';const meta=report.meta||report.date;c.fillText(ellipsis(c,meta,820),PAGE.W/2,264);if(pageCount>1){c.textAlign='left';c.font='700 13px Tahoma,Arial';c.fillStyle='#8a7657';c.fillText(`صفحة ${pageNo} من ${pageCount}`,PAGE.M,294)}c.strokeStyle='#e3d7c2';c.beginPath();c.moveTo(PAGE.M,302);c.lineTo(PAGE.W-PAGE.M,302);c.stroke()}
function drawCard(c,box){const {sec,x,y,w,h}=box;cardBox(c,x,y,w,h,14,'#fffdfa','#e5d8c1',true);const grad=c.createLinearGradient(x,y,x+w,y);grad.addColorStop(0,'#a97626');grad.addColorStop(.55,'#c2933c');grad.addColorStop(1,'#a97626');c.save();pathRound(c,x,y,w,48,14);c.clip();c.fillStyle=grad;c.fillRect(x,y,w,48);c.fillStyle=grad;c.fillRect(x,y+25,w,23);c.restore();c.direction='rtl';c.textAlign='right';c.fillStyle='#fff';c.font='800 20px Tahoma,Arial';const title=sec.part?`${sec.title} — تابع`:sec.title;c.fillText(ellipsis(c,title,w-28),x+w-14,y+31);let yy=y+50;if(sec.type==='simple'){sec.items.forEach((it,idx)=>{if(idx){c.strokeStyle='#eee5d5';c.beginPath();c.moveTo(x+10,yy);c.lineTo(x+w-10,yy);c.stroke()}const cy=yy+21;c.textAlign='right';c.fillStyle='#312a22';fit(c,it.name,w-118,17,11,'700');c.fillText(ellipsis(c,it.name,w-118),x+w-12,cy);c.textAlign='left';c.fillStyle='#9a6c20';c.font='800 16px Tahoma,Arial';c.fillText(ellipsis(c,`${it.value} ${it.unit}`,104),x+12,cy);yy+=32})}else if(sec.type==='flow'){sec.items.forEach((it,idx)=>{if(idx){c.strokeStyle='#eee5d5';c.beginPath();c.moveTo(x+10,yy);c.lineTo(x+w-10,yy);c.stroke()}c.textAlign='right';c.fillStyle='#302920';fit(c,it.name,w-24,16,11,'800');c.fillText(ellipsis(c,it.name,w-24),x+w-12,yy+17);c.fillStyle='#796d5d';c.font='11px Tahoma,Arial';const metrics=`أول ${it.opening}  •  وارد ${it.incoming}  •  آخر ${it.closing}  •  مباع ${it.sold} ${it.unit}`;c.fillText(ellipsis(c,metrics,w-24),x+w-12,yy+36);yy+=44})}else{c.textAlign='right';c.fillStyle='#4a4034';c.font='15px Tahoma,Arial';const words=String(sec.items[0]?.name||'').split(' ');let line='',lines=[];for(const word of words){const next=line?line+' '+word:word;if(c.measureText(next).width>w-28&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);lines.slice(0,3).forEach((ln,i)=>c.fillText(ln,x+w-14,yy+27+i*22))}}
function drawFooter(c,pageNo,pageCount){c.strokeStyle='#e4d8c3';c.beginPath();c.moveTo(PAGE.M,PAGE.H-64);c.lineTo(PAGE.W-PAGE.M,PAGE.H-64);c.stroke();c.fillStyle='#887b69';c.font='13px Tahoma,Arial';c.textAlign='center';c.direction='rtl';c.fillText(`نظام الجرد اليومي · مطاعم الدمشقية${pageCount>1?` · ${pageNo}/${pageCount}`:''}`,PAGE.W/2,PAGE.H-35)}
async function canvasesFor(report){await document.fonts.ready;const logo=await image('/inventory/inventory-brands-banner.webp?v=9'),pages=layout(report),out=[];pages.forEach((p,idx)=>{const cv=document.createElement('canvas');cv.width=PAGE.W;cv.height=PAGE.H;const c=cv.getContext('2d');c.fillStyle='#fbf7ef';c.fillRect(0,0,PAGE.W,PAGE.H);drawBorder(c);drawHeader(c,report,logo,idx+1,pages.length);p.cards.forEach(box=>drawCard(c,box));drawFooter(c,idx+1,pages.length);out.push(cv)});return out}
const blobOf=cv=>new Promise((resolve,reject)=>cv.toBlob(b=>b?resolve(b):reject(new Error('تعذر إنشاء الصورة')),'image/jpeg',.94));
async function downloadFiles(files){for(const f of files){const url=URL.createObjectURL(f),a=document.createElement('a');a.href=url;a.download=f.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2500);await new Promise(r=>setTimeout(r,120))}}
async function make(share){const report=currentReport();if(!report.sections.length&&!report.notes)return toast('لا توجد بيانات مدخلة لإنشاء التقرير',true);try{toast('جاري تجهيز التقرير الاحترافي...');const cvs=await canvasesFor(report),safe=report.branch.replace(/\s+/g,'-').replace(/[^\u0600-\u06FF\w-]/g,''),files=[];for(let i=0;i<cvs.length;i++){const b=await blobOf(cvs[i]),suffix=cvs.length>1?`-${i+1}`:'';files.push(new File([b],`جرد-${safe}-${report.date}${suffix}.jpg`,{type:'image/jpeg'}))}if(share&&navigator.share&&(!navigator.canShare||navigator.canShare({files}))){await navigator.share({files,title:'تقرير الجرد اليومي',text:`${report.branch} - ${report.date}`});toast(files.length>1?`تم تجهيز ${files.length} صفحات للمشاركة`:'تم تجهيز التقرير للمشاركة');return}await downloadFiles(files);if(share){setTimeout(()=>window.open('https://wa.me/?text='+encodeURIComponent(`تقرير الجرد اليومي - ${report.branch} - ${report.date}`),'_blank'),250);toast(files.length>1?`تم تنزيل ${files.length} صور وفتح واتساب`:'تم تنزيل التقرير وفتح واتساب')}else toast(files.length>1?`تم إنشاء ${files.length} صور 9:16`:'تم إنشاء التقرير 9:16')}catch(e){if(e?.name==='AbortError')return;toast(e.message||'تعذر إنشاء التقرير',true)}}
document.addEventListener('click',e=>{const b=e.target.closest?.('#jpg,#share');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();make(b.id==='share')},true);
})();
