(()=>{'use strict';
const VER='report-v26';
if(window.__reportV26Loaded)return;window.__reportV26Loaded=true;
const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const txt=el=>String(el?.textContent||'').trim();
const hasVal=el=>!!el&&el.value!==''&&el.value!==null&&el.value!==undefined;
const PAGE={W:1080,H:1920,M:38,BOTTOM:1836,GAP:14,COLS:3,TOP:206,TOP_APP:308};
PAGE.CW=(PAGE.W-PAGE.M*2-PAGE.GAP*(PAGE.COLS-1))/PAGE.COLS;
function toast(msg,bad=false){let t=document.querySelector('.report-v26-toast');if(!t){t=document.createElement('div');t.className='report-v26-toast';Object.assign(t.style,{position:'fixed',left:'18px',bottom:'86px',zIndex:'99999',padding:'10px 14px',borderRadius:'10px',font:'700 12px Tahoma,Arial',color:'#fff',background:'#2f2a23',boxShadow:'0 8px 24px rgba(0,0,0,.18)',transition:'.18s',opacity:'0'});document.body.appendChild(t)}t.textContent=msg;t.style.background=bad?'#9f433b':'#2f2a23';t.style.opacity='1';clearTimeout(window.__rv26);window.__rv26=setTimeout(()=>t.style.opacity='0',2800)}
function previousDay(iso){try{const d=new Date(iso+'T12:00:00+03:00');d.setDate(d.getDate()-1);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}catch{return iso}}
function dateParts(iso){try{const d=new Date(iso+'T12:00:00+03:00');const weekday=new Intl.DateTimeFormat('ar-SA',{weekday:'long',timeZone:'Asia/Riyadh'}).format(d);const hijri=new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{year:'numeric',month:'long',day:'numeric',timeZone:'Asia/Riyadh'}).format(d);return{weekday,hijri}}catch{return{weekday:'',hijri:''}}}
function currentReport(){const branch=txt(document.querySelector('.head h2'))||'الفرع';const notes=(document.querySelector('#notes')?.value||'').trim();const sourceDate=document.querySelector('#rd')?.value||new Date().toISOString().slice(0,10);const reportDate=previousDay(sourceDate);const sections=qsa('.section').map(sec=>{const title=txt(sec.querySelector('.sectitle h3'))||'قسم';const table=sec.querySelector('table.flow');if(table){const items=qsa('tbody tr',table).map(row=>{const closing=row.querySelector('input[data-key="closing"]');if(!hasVal(closing))return null;const cells=row.querySelectorAll('td');return{name:txt(cells[0]),opening:txt(row.querySelector('.ro'))||'0',incoming:String(row.querySelector('input[data-key="incoming"]')?.value||'0'),closing:String(closing.value),sold:txt(row.querySelector('.sold'))||'—',unit:txt(cells[cells.length-1])}}).filter(Boolean);return items.length?{title,type:'flow',items}:null}const items=qsa('.item',sec).map(card=>{const input=card.querySelector('input[data-key="value"]');if(!hasVal(input))return null;return{name:txt(card.querySelector('.name')),value:String(input.value),unit:txt(card.querySelector('.unit'))}}).filter(Boolean);return items.length?{title,type:'simple',items}:null}).filter(Boolean);return{branch,notes,sections,sourceDate,reportDate}}
function themeFor(report){const mazaq=report.branch.includes('المذاق');return mazaq?{
 mode:'mazaq',paper:'#f7f7f6',surface:'#ffffff',accent:'#9b2028',accentDark:'#6f171d',text:'#292b2e',muted:'#62656a',line:'#d8d9db',soft:'#eeeeef',stripe:'#f6f6f6',appBg:'#f1f1f2',appStroke:'#b7b9bd',appValue:'#9b2028',footer:'#72757a'
}:{
 mode:'grill',paper:'#fbf7ef',surface:'#fffdfa',accent:'#b88932',accentDark:'#8e6524',text:'#2f2922',muted:'#756958',line:'#e3d5bc',soft:'#f2e8d8',stripe:'#fcf7ee',appBg:'#fff7e8',appStroke:'#d8b873',appValue:'#9a6c20',footer:'#8b7d6c'
}}
function pathRound(c,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+rr,y);c.arcTo(x+w,y,x+w,y+h,rr);c.arcTo(x+w,y+h,x,y+h,rr);c.arcTo(x,y+h,x,y,rr);c.arcTo(x,y,x+w,y,rr);c.closePath()}
function cardBox(c,x,y,w,h,r,fill,stroke,shadow=true){c.save();if(shadow){c.shadowColor='rgba(45,38,30,.09)';c.shadowBlur=9;c.shadowOffsetY=3}pathRound(c,x,y,w,h,r);c.fillStyle=fill;c.fill();c.restore();if(stroke){pathRound(c,x,y,w,h,r);c.strokeStyle=stroke;c.lineWidth=1.2;c.stroke()}}
function fit(c,text,max,size=22,min=13,weight='700'){let s=size;for(;s>min;s--){c.font=`${weight} ${s}px Tahoma,Arial`;if(c.measureText(String(text)).width<=max)break}return s}
function ellipsis(c,text,max){let s=String(text);if(c.measureText(s).width<=max)return s;while(s.length>2&&c.measureText(s+'…').width>max)s=s.slice(0,-1);return s+'…'}
function rowH(sec){return sec.type==='flow'?60:sec.type==='notes'?110:52}
function cardH(sec){return 66+sec.items.length*rowH(sec)+10}
function appInfo(report){if(!/المشويات أفراد|المذاق الدمشقي/.test(report.branch))return null;const sec=report.sections.find(s=>s.title==='تقرير التطبيق');if(!sec||!sec.items.length)return null;const it=sec.items[0];return{label:'عدد طلبات التطبيق',value:it.value,unit:it.unit||'طلب'}}
function splitSections(report){const app=report.sections.find(s=>s.title==='تقرير التطبيق');const source=report.sections.filter(s=>s!==app);if(report.notes)source.push({title:'ملاحظات',type:'notes',items:[{name:report.notes}]});const out=[];for(const sec of source){const rh=rowH(sec),max=Math.max(1,Math.floor((PAGE.BOTTOM-PAGE.TOP-80)/rh));for(let i=0;i<sec.items.length;i+=max){out.push({title:sec.title,type:sec.type,items:sec.items.slice(i,i+max),part:i===0?0:Math.floor(i/max)+1})}}return out}
function layout(report){const chunks=splitSections(report),pages=[];const app=appInfo(report);let page=null,first=true;function fresh(){const top=first&&app?PAGE.TOP_APP:PAGE.TOP;page={ys:Array(PAGE.COLS).fill(top),cards:[],app:first?app:null};pages.push(page);first=false}fresh();for(const sec of chunks){const h=cardH(sec);let order=page.ys.map((y,i)=>({y,i})).sort((a,b)=>a.y-b.y),slot=order.find(o=>o.y+h<=PAGE.BOTTOM);if(!slot){fresh();order=page.ys.map((y,i)=>({y,i})).sort((a,b)=>a.y-b.y);slot=order[0]}const col=slot.i,x=PAGE.M+(PAGE.COLS-1-col)*(PAGE.CW+PAGE.GAP),y=page.ys[col];page.cards.push({sec,x,y,w:PAGE.CW,h});page.ys[col]=y+h+PAGE.GAP}return pages}
function drawBorder(c,t){c.strokeStyle=t.accent;c.lineWidth=2.2;pathRound(c,10,10,PAGE.W-20,PAGE.H-20,24);c.stroke();c.strokeStyle=t.mode==='mazaq'?'#d7d8da':'#ead8b4';c.lineWidth=1;pathRound(c,19,19,PAGE.W-38,PAGE.H-38,19);c.stroke()}
function drawAppCard(c,app,t){const x=PAGE.M,y=171,w=PAGE.W-PAGE.M*2,h=113;cardBox(c,x,y,w,h,17,t.appBg,t.appStroke,false);c.fillStyle=t.accent;c.fillRect(x,y,6,h);c.direction='rtl';c.textAlign='right';c.fillStyle=t.text;c.font='800 27px Tahoma,Arial';c.fillText(app.label,x+w-26,y+42);c.textAlign='left';c.fillStyle=t.appValue;c.font='900 55px Tahoma,Arial';c.fillText(String(app.value),x+31,y+72);c.fillStyle=t.muted;c.font='700 18px Tahoma,Arial';c.fillText(app.unit||'طلب',x+31,y+98)}
function drawHeader(c,report,pageNo,pageCount,app,t){const d=dateParts(report.reportDate);c.direction='rtl';c.textAlign='right';c.fillStyle=t.accent;c.font='900 52px Tahoma,Arial';c.fillText(report.branch,PAGE.W-PAGE.M,69);c.fillStyle=t.text;c.font='900 36px Tahoma,Arial';c.fillText('تقرير الجرد اليومي',PAGE.W-PAGE.M,118);c.textAlign='left';c.fillStyle=t.text;c.font='900 34px Tahoma,Arial';c.fillText(d.weekday,PAGE.M,59);c.fillStyle=t.accentDark;c.font='900 30px Tahoma,Arial';c.fillText(report.reportDate,PAGE.M,99);c.fillStyle=t.muted;c.font='700 22px Tahoma,Arial';c.fillText(d.hijri,PAGE.M,132);c.strokeStyle=t.line;c.lineWidth=1.4;c.beginPath();c.moveTo(PAGE.M,153);c.lineTo(PAGE.W-PAGE.M,153);c.stroke();if(app)drawAppCard(c,app,t);if(pageCount>1){c.direction='rtl';c.textAlign='left';c.fillStyle=t.muted;c.font='700 14px Tahoma,Arial';c.fillText(`صفحة ${pageNo} من ${pageCount}`,PAGE.M,164)}}
function drawSimpleRow(c,it,x,yy,w,idx,t){if(idx%2===1){c.fillStyle=t.stripe;c.fillRect(x+7,yy,w-14,52)}if(idx){c.strokeStyle=t.mode==='mazaq'?'#e5e6e7':'#eee4d4';c.beginPath();c.moveTo(x+10,yy);c.lineTo(x+w-10,yy);c.stroke()}c.direction='rtl';const nameX=x+w-14,valueX=x+120,unitX=x+18;c.textAlign='right';c.fillStyle=t.text;fit(c,it.name,w-152,21,14,'700');c.fillText(ellipsis(c,it.name,w-152),nameX,yy+33);c.direction='ltr';c.textAlign='right';c.fillStyle=t.accent;c.font='800 21px Tahoma,Arial';c.fillText(String(it.value),valueX,yy+33);c.textAlign='left';c.fillStyle=t.muted;c.font='600 16px Tahoma,Arial';c.fillText(String(it.unit||''),unitX,yy+33)}
function drawFlowRow(c,it,x,yy,w,idx,t){if(idx%2===1){c.fillStyle=t.stripe;c.fillRect(x+7,yy,w-14,60)}if(idx){c.strokeStyle=t.mode==='mazaq'?'#e5e6e7':'#eee4d4';c.beginPath();c.moveTo(x+10,yy);c.lineTo(x+w-10,yy);c.stroke()}c.direction='rtl';c.textAlign='right';c.fillStyle=t.text;fit(c,it.name,w-24,19,13,'800');c.fillText(ellipsis(c,it.name,w-24),x+w-12,yy+23);c.fillStyle=t.muted;c.font='600 14px Tahoma,Arial';const metrics=`أول ${it.opening} | وارد ${it.incoming} | آخر ${it.closing} | مباع ${it.sold} ${it.unit}`;c.fillText(ellipsis(c,metrics,w-24),x+w-12,yy+47)}
function drawCard(c,box,t){const {sec,x,y,w,h}=box;cardBox(c,x,y,w,h,15,t.surface,t.line,true);c.save();pathRound(c,x,y,w,64,15);c.clip();c.fillStyle=t.mode==='mazaq'?t.accentDark:t.accent;c.fillRect(x,y,w,64);c.fillRect(x,y+32,w,32);if(t.mode==='mazaq'){c.fillStyle=t.accent;c.fillRect(x,y,w,5)}c.restore();c.direction='rtl';c.textAlign='center';c.fillStyle='#fff';c.font='800 30px Tahoma,Arial';const title=sec.part?`${sec.title} — تابع`:sec.title;c.fillText(ellipsis(c,title,w-24),x+w/2,y+42);let yy=y+66;if(sec.type==='simple'){sec.items.forEach((it,idx)=>{drawSimpleRow(c,it,x,yy,w,idx,t);yy+=52})}else if(sec.type==='flow'){sec.items.forEach((it,idx)=>{drawFlowRow(c,it,x,yy,w,idx,t);yy+=60})}else{c.direction='rtl';c.textAlign='right';c.fillStyle=t.text;c.font='600 19px Tahoma,Arial';const words=String(sec.items[0]?.name||'').split(' ');let line='',lines=[];for(const word of words){const next=line?line+' '+word:word;if(c.measureText(next).width>w-30&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);lines.slice(0,4).forEach((ln,i)=>c.fillText(ln,x+w-15,yy+32+i*28))}}
function drawFooter(c,pageNo,pageCount,t){c.strokeStyle=t.line;c.beginPath();c.moveTo(PAGE.M,PAGE.H-62);c.lineTo(PAGE.W-PAGE.M,PAGE.H-62);c.stroke();c.fillStyle=t.footer;c.font='13px Tahoma,Arial';c.textAlign='center';c.direction='rtl';c.fillText(`نظام الجرد اليومي${pageCount>1?` · ${pageNo}/${pageCount}`:''}`,PAGE.W/2,PAGE.H-34)}
async function canvasesFor(report){await document.fonts.ready;const pages=layout(report),out=[],t=themeFor(report);pages.forEach((p,idx)=>{const cv=document.createElement('canvas');cv.width=PAGE.W;cv.height=PAGE.H;const c=cv.getContext('2d');c.fillStyle=t.paper;c.fillRect(0,0,PAGE.W,PAGE.H);drawBorder(c,t);drawHeader(c,report,idx+1,pages.length,p.app,t);p.cards.forEach(box=>drawCard(c,box,t));drawFooter(c,idx+1,pages.length,t);out.push(cv)});return out}
const blobOf=cv=>new Promise((resolve,reject)=>cv.toBlob(b=>b?resolve(b):reject(new Error('تعذر إنشاء الصورة')),'image/jpeg',.95));
async function downloadFiles(files){for(const f of files){const url=URL.createObjectURL(f),a=document.createElement('a');a.href=url;a.download=f.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2500);await new Promise(r=>setTimeout(r,120))}}
async function make(share){const report=currentReport();if(!report.sections.length&&!report.notes)return toast('لا توجد بيانات مدخلة لإنشاء التقرير',true);try{toast('جاري تجهيز التقرير...');const cvs=await canvasesFor(report),safe=report.branch.replace(/\s+/g,'-').replace(/[^\u0600-\u06FF\w-]/g,''),files=[];for(let i=0;i<cvs.length;i++){const b=await blobOf(cvs[i]),suffix=cvs.length>1?`-${i+1}`:'';files.push(new File([b],`جرد-${safe}-${report.reportDate}${suffix}.jpg`,{type:'image/jpeg'}))}if(share&&navigator.share&&(!navigator.canShare||navigator.canShare({files}))){await navigator.share({files,title:'تقرير الجرد اليومي',text:`${report.branch} - ${report.reportDate}`});toast(files.length>1?`تم تجهيز ${files.length} صفحات للمشاركة`:'تم تجهيز التقرير للمشاركة');return}await downloadFiles(files);if(share){setTimeout(()=>window.open('https://wa.me/?text='+encodeURIComponent(`تقرير الجرد اليومي - ${report.branch} - ${report.reportDate}`),'_blank'),250);toast(files.length>1?`تم تنزيل ${files.length} صور وفتح واتساب`:'تم تنزيل التقرير وفتح واتساب')}else toast(files.length>1?`تم إنشاء ${files.length} صور 9:16`:'تم إنشاء التقرير 9:16')}catch(e){if(e?.name==='AbortError')return;toast(e.message||'تعذر إنشاء التقرير',true)}}
document.addEventListener('click',e=>{const b=e.target.closest?.('#jpg,#share');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();make(b.id==='share')},true);
})();
