(()=>{'use strict';
const VER='report-v17';
let timer=null;
const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const txt=(el)=>String(el?.textContent||'').trim();
const hasVal=(el)=>!!el&&el.value!==''&&el.value!==null&&el.value!==undefined;
function toast(msg,bad=false){let t=document.querySelector('.report-v17-toast');if(!t){t=document.createElement('div');t.className='report-v17-toast';Object.assign(t.style,{position:'fixed',left:'18px',bottom:'86px',zIndex:'9999',padding:'10px 14px',borderRadius:'10px',font:'700 12px Tahoma,Arial',color:'#fff',background:'#2f2a23',boxShadow:'0 8px 24px rgba(0,0,0,.18)',transition:'.18s',opacity:'0'});document.body.appendChild(t)}t.textContent=msg;t.style.background=bad?'#9f433b':'#2f2a23';t.style.opacity='1';clearTimeout(window.__rv17);window.__rv17=setTimeout(()=>t.style.opacity='0',2600)}
function currentReport(){const branch=txt(document.querySelector('.head h2'))||'الفرع';const meta=txt(document.querySelector('.head .muted'));const notes=(document.querySelector('#notes')?.value||'').trim();const sections=qsa('.section').map(sec=>{const title=txt(sec.querySelector('.sectitle h3'))||'قسم';const table=sec.querySelector('table.flow');if(table){const items=qsa('tbody tr',table).map(row=>{const closing=row.querySelector('input[data-key="closing"]');if(!hasVal(closing))return null;const cells=row.querySelectorAll('td');return{name:txt(cells[0]),opening:txt(row.querySelector('.ro'))||'0',incoming:String(row.querySelector('input[data-key="incoming"]')?.value||'0'),closing:String(closing.value),sold:txt(row.querySelector('.sold'))||'—',unit:txt(cells[cells.length-1])}}).filter(Boolean);return items.length?{title,type:'flow',items}:null}const items=qsa('.item',sec).map(card=>{const input=card.querySelector('input[data-key="value"]');if(!hasVal(input))return null;return{name:txt(card.querySelector('.name')),value:String(input.value),unit:txt(card.querySelector('.unit'))}}).filter(Boolean);return items.length?{title,type:'simple',items}:null}).filter(Boolean);return{branch,meta,notes,sections}}
function rr(c,x,y,w,h,r,fill,stroke){c.beginPath();c.roundRect(x,y,w,h,r);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}}
function setFontFit(c,text,max,size=22,min=16,weight='700'){let s=size;for(;s>min;s--){c.font=`${weight} ${s}px Tahoma,Arial`;if(c.measureText(text).width<=max)break}return s}
function sectionHeight(sec,W){if(sec.type==='flow')return 58+Math.ceil(sec.items.length/2)*64+18;return 58+Math.ceil(sec.items.length/3)*54+18}
function image(src){return new Promise(res=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>res(null);im.src=src})}
async function drawReport(report){await document.fonts.ready;const W=1400,M=64,CW=W-M*2,topH=300;let H=topH+report.sections.reduce((n,s)=>n+sectionHeight(s,W)+14,0)+(report.notes?112:0)+74;H=Math.max(820,Math.min(H,10000));const cv=document.createElement('canvas');cv.width=W;cv.height=H;const c=cv.getContext('2d');c.fillStyle='#fbf7ef';c.fillRect(0,0,W,H);c.fillStyle='#b78b42';c.fillRect(0,0,W,12);c.direction='rtl';c.textAlign='right';const logo=await image('/inventory/inventory-brands-banner.webp?v=9');if(logo){const lw=470,lh=98;c.drawImage(logo,(W-lw)/2,34,lw,lh)}c.fillStyle='#2e281f';c.font='800 42px Tahoma,Arial';c.fillText('تقرير الجرد اليومي',W-M,178);c.fillStyle='#a57931';c.font='800 34px Tahoma,Arial';c.fillText(report.branch,W-M,226);c.fillStyle='#746b60';c.font='21px Tahoma,Arial';c.fillText(report.meta||'',W-M,265);c.strokeStyle='#e1d4bd';c.lineWidth=1;c.beginPath();c.moveTo(M,286);c.lineTo(W-M,286);c.stroke();let y=310;for(const sec of report.sections){const sh=sectionHeight(sec,W);rr(c,M,y,CW,sh,16,'#fffdfa','#e5d7bf');c.fillStyle='#f1e3c6';c.fillRect(M,y,CW,48);c.fillStyle='#5b421b';c.font='800 27px Tahoma,Arial';c.textAlign='right';c.fillText(sec.title,W-M-18,y+33);c.fillStyle='#8a7658';c.font='18px Tahoma,Arial';c.textAlign='left';c.fillText(`${sec.items.length} صنف`,M+18,y+32);const sy=y+58;if(sec.type==='simple'){const gap=12,cols=3,cw=(CW-gap*(cols-1))/cols,rh=54;sec.items.forEach((it,i)=>{const col=i%cols,row=Math.floor(i/cols),x=W-M-cw-col*(cw+gap),yy=sy+row*rh;rr(c,x,yy,cw,44,9,'#fff','#eee3d0');c.direction='rtl';c.textAlign='right';c.fillStyle='#30291f';setFontFit(c,it.name,cw-145,21,15,'700');c.fillText(it.name,x+cw-12,yy+29);c.fillStyle='#a47730';c.textAlign='left';c.font='800 20px Tahoma,Arial';c.fillText(`${it.value} ${it.unit}`,x+12,yy+29)})}else{const gap=14,cols=2,cw=(CW-gap)/2,rh=64;sec.items.forEach((it,i)=>{const col=i%2,row=Math.floor(i/2),x=W-M-cw-col*(cw+gap),yy=sy+row*rh;rr(c,x,yy,cw,54,9,'#fff','#eee3d0');c.direction='rtl';c.textAlign='right';c.fillStyle='#30291f';setFontFit(c,it.name,cw-26,20,15,'800');c.fillText(it.name,x+cw-12,yy+22);c.fillStyle='#776b5c';c.font='16px Tahoma,Arial';c.fillText(`أول ${it.opening}  •  وارد ${it.incoming}  •  آخر ${it.closing}  •  مباع ${it.sold} ${it.unit}`,x+cw-12,yy+44)})}y+=sh+14}
if(report.notes){rr(c,M,y,CW,92,14,'#fffaf0','#e5d7bf');c.direction='rtl';c.textAlign='right';c.fillStyle='#7a5a24';c.font='800 20px Tahoma,Arial';c.fillText('ملاحظات التقرير',W-M-18,y+28);c.fillStyle='#4c443a';c.font='18px Tahoma,Arial';let note=report.notes;if(c.measureText(note).width>CW-36){while(note.length>10&&c.measureText(note+'…').width>CW-36)note=note.slice(0,-1);note+='…'}c.fillText(note,W-M-18,y+61);y+=106}c.strokeStyle='#e1d4bd';c.beginPath();c.moveTo(M,H-58);c.lineTo(W-M,H-58);c.stroke();c.fillStyle='#8b8173';c.font='16px Tahoma,Arial';c.textAlign='center';c.fillText('نظام الجرد اليومي · مطاعم الدمشقية',W/2,H-27);return cv}
const blobOf=cv=>new Promise((resolve,reject)=>cv.toBlob(b=>b?resolve(b):reject(new Error('تعذر إنشاء الصورة')),'image/jpeg',.94));
async function make(share){const r=currentReport();if(!r.sections.length)return toast('لا توجد بيانات مدخلة لإنشاء التقرير',true);try{toast('جاري تجهيز التقرير...');const cv=await drawReport(r),blob=await blobOf(cv),safe=r.branch.replace(/\s+/g,'-').replace(/[^\u0600-\u06FF\w-]/g,''),date=(document.querySelector('#rd')?.value||new Date().toISOString().slice(0,10)),name=`جرد-${safe}-${date}.jpg`,file=new File([blob],name,{type:'image/jpeg'});if(share&&navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:'تقرير الجرد اليومي',text:`${r.branch} - ${date}`});toast('تم تجهيز التقرير للمشاركة');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);if(share){setTimeout(()=>window.open('https://wa.me/?text='+encodeURIComponent(`تقرير الجرد اليومي - ${r.branch} - ${date}`),'_blank'),250);toast('تم تنزيل التقرير وفتح واتساب')}else toast('تم إنشاء التقرير')}catch(e){toast(e.message||'تعذر إنشاء التقرير',true)}}
function bind(){const jpg=document.querySelector('#jpg'),share=document.querySelector('#share');if(jpg&&jpg.dataset.reportV17!=='1'){jpg.dataset.reportV17='1';jpg.onclick=()=>make(false)}if(share&&share.dataset.reportV17!=='1'){share.dataset.reportV17='1';share.onclick=()=>make(true)}}
function schedule(){clearTimeout(timer);timer=setTimeout(bind,40)}
new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
